In [33]:
import pandas as pd
import csv

In [34]:
planets = pd.read_csv("./planetary_systems.csv", skiprows=1)
planets.dropna(inplace=True)
planets.reset_index(inplace=True)
planets.drop("index", axis=1, inplace=True)

In [35]:
planets.columns

Index(['pl_controv_flag', 'pl_name', 'hostname', 'sy_snum', 'sy_pnum',
       'discoverymethod', 'disc_year', 'disc_facility', 'pl_orbper',
       'pl_orbsmax', 'pl_rade', 'pl_bmasse', 'pl_orbeccen', 'pl_eqt',
       'st_spectype', 'st_teff', 'st_rad', 'st_mass', 'st_met', 'st_metratio',
       'st_logg', 'rastr', 'ra', 'decstr', 'dec', 'sy_dist', 'sy_vmag',
       'sy_kmag', 'sy_gaiamag'],
      dtype='object')

In [36]:
planets

,pl_controv_flag,pl_name,hostname,sy_snum,sy_pnum,discoverymethod,disc_year,disc_facility,pl_orbper,pl_orbsmax,...,st_metratio,st_logg,rastr,ra,decstr,dec,sy_dist,sy_vmag,sy_kmag,sy_gaiamag
0,0.0,51 Eri b,51 Eri,3,1,Imaging,2015,Gemini Observatory,11688,13.2,...,[M/H],4.31,04h37m36.18s,69.4007424,-02d28m25.77s,-2.4738245,29.7575,5.21149,4.537,5.15806
1,0.0,55 Cnc b,55 Cnc,2,5,Radial Velocity,1996,Lick Observatory,14.6516,0.1134,...,[Fe/H],4.43,08h52m35.24s,133.1468373,+28d19m47.34s,28.3298154,12.5855,5.95084,4.015,5.72973
2,0.0,55 Cnc e,55 Cnc,2,5,Radial Velocity,2004,McDonald Observatory,0.7365474,0.01544,...,[Fe/H],4.43,08h52m35.24s,133.1468373,+28d19m47.34s,28.3298154,12.5855,5.95084,4.015,5.72973
3,0.0,AF Lep b,AF Lep,1,1,Imaging,2023,Paranal Observatory,8030,8.4,...,[Fe/H],4.4,05h27m04.78s,81.7699216,-11d54m04.23s,-11.9011752,26.8564,6.332,4.926,6.18644
4,0.0,AU Mic b,AU Mic,1,3,Transit,2020,Transiting Exoplanet Survey Satellite (TESS),8.4629991,0.0645,...,[M/H],4.4,20h45m09.87s,311.2911369,-31d20m32.82s,-31.34245,9.7221,8.81,4.529,7.84038
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
856,0.0,YZ Cet d,YZ Cet,1,3,Radial Velocity,2017,La Silla Observatory,4.65626,0.02851,...,[Fe/H],5.17,01h12m31.94s,18.1330792,-16d59m46.48s,-16.9962434,3.71207,12.074,6.42,10.4294
857,0.0,bet Pic b,bet Pic,1,2,Imaging,2008,Paranal Observatory,8617.50952,10.018,...,[Fe/H],4.35,05h47m17.10s,86.8212337,-51d03m58.13s,-51.066148,19.7442,3.85,3.526,3.82015
858,0.0,pi Men c,HD 39091,1,3,Transit,2018,Transiting Exoplanet Survey Satellite (TESS),6.26791,0.069,...,[Fe/H],4.36,05h37m11.83s,84.2992798,-80d27m52.57s,-80.4646041,18.2702,5.65,4.241,5.5128
859,1.0,rho CrB b,rho CrB,1,4,Radial Velocity,1997,Fred Lawrence Whipple Observatory,39.8438,0.2245,...,[Fe/H],4.25,16h01m02.42s,240.2600639,+33d18m00.67s,33.3001861,17.4671,5.40816,3.857,5.24167
860,0.0,rho CrB c,rho CrB,1,4,Radial Velocity,2016,Multiple Observatories,102.19,0.4206,...,[Fe/H],4.25,16h01m02.42s,240.2600639,+33d18m00.67s,33.3001861,17.4671,5.40816,3.857,5.24167

In [37]:
result = planets.loc[:, ['sy_snum', 'sy_pnum', 'pl_orbper', 'pl_orbsmax']]
result

    sy_snum sy_pnum   pl_orbper pl_orbsmax
0         3       1       11688       13.2
1         2       5     14.6516     0.1134
2         2       5   0.7365474    0.01544
3         1       1        8030        8.4
4         1       3   8.4629991     0.0645
..      ...     ...         ...        ...
856       1       3     4.65626    0.02851
857       1       2  8617.50952     10.018
858       1       3     6.26791      0.069
859       1       4     39.8438     0.2245
860       1       4      102.19     0.4206

[861 rows x 4 columns]

In [38]:
result.head(2)

  sy_snum sy_pnum pl_orbper pl_orbsmax
0       3       1     11688       13.2
1       2       5   14.6516     0.1134

In [39]:
from sklearn.metrics.pairwise import cosine_similarity, cosine_distances

In [40]:
cosine_similarity(result.loc["0":"0"],[[3,2,5,4]])

array([[0.68115618]])

In [43]:
def cosine_calculations(dataframe):
    exoplanet_similarity={}
    for index in range(len(dataframe)):
        level_of_similarity = cosine_similarity(dataframe.loc[index:index], [[3,2,5,4]])
        exoplanet_similarity[index] = level_of_similarity[0][0] 
    
    sorted_list = sorted(exoplanet_similarity.items(), key=lambda item: item[1], reverse=True)
    sorted_dict_by_similarity = dict(sorted_list) 

    top_five = dict(list(sorted_dict_by_similarity.items())[:5])
    keys_list = list(top_five.keys()) 
    planet_names = planets.loc[keys_list, "pl_name"].tolist()  

    return planet_names

In [44]:
cosine_calculations(result)

['KELT-18 b', 'MASCARA-4 b', 'HATS-30 b', 'WASP-100 b', 'WASP-123 b']